---
title: "pm2.5"
author: "leon_x123"
date: "23 May 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## read data
```{r}
Sys.setlocale("LC_CTYPE", locale="Chinese")
# library(readr)
# pm_patients_df <- as.data.frame(read_csv("C:/Users/ASUS/Downloads/Age_County_Gender_010.csv"))
```

reading multi worksheet from xlsx
```{r}
library(XLConnect)

pm_importWorksheets <- function(filename) {
    # filename: name of Excel file
    workbook <- loadWorkbook(filename)
    sheet_names <- getSheets(workbook)
    names(sheet_names) <- sheet_names
    sheet_list <- lapply(sheet_names, function(.sheet){
        readWorksheet(object=workbook, .sheet)})
}

pm_death_list <- pm_importWorksheets(filename = "C:/Users/ASUS/Downloads/1.2-24各縣市肺炎死亡概況.xls")
pm_death_list2 <- pm_importWorksheets(filename = "C:/Users/ASUS/Downloads/1.2-25各縣市慢性下呼吸道疾病死亡概況.xls")
# pm_death_100 <- pm_death_list[[7]]
# pm_death_99 <- pm_death_list[[8]]
# pm_death_98 <- pm_death_list[[9]]
# pm_death_97 <- pm_death_list[[10]]
# pm_death_96 <- pm_death_list[[11]]
# pm_death_95 <- pm_death_list[[12]]
# pm_death_94 <- pm_death_list[[13]]
# pm_death_93 <- pm_death_list[[14]]
# pm_death_92 <- pm_death_list[[15]]
```

## tidy data
#others
```{r}
# library("tidyr")
# 
# pm_people_df_list <- list(pm_people_df_1, pm_people_df_2, pm_people_df_3, pm_people_df_4, pm_people_df_5,
#                       pm_people_df_6, pm_people_df_7, pm_people_df_8, pm_people_df_9, pm_people_df_10,
#                       pm_people_df_11, pm_people_df_12, pm_people_df_13, pm_people_df_14, pm_people_df_15,
#                       pm_people_df_16, pm_people_df_17, pm_people_df_18, pm_people_df_19, pm_people_df_20,
#                       pm_people_df_21, pm_people_df_22)
# for(i in 1:22){
#  #print(pm_people_df_list[[i]])
#  pm_a <- pm_people_df_list[[i]][3, 1]
#  pm_people_df_list[[i]] <- pm_people_df_list[[i]][c(-1:-3), ]
#  colnames(pm_people_df_list[[i]]) <- c("region", "house", "people", "M", "F")
#  pm_people_df_list[[i]] <- drop_na(data.frame(county = pm_a, pm_people_df_list[[i]]))
#  #print(pm_people_df_list[[i]])
# }
# 
# pm_people_df_all <- 0
# for(i in 1:22){
#  pm_people_df_all <- rbind(pm_people_df_all, pm_people_df_list[[i]])
# }
# pm_people_df_all <- pm_people_df_all[-1, ]
# 
# rm(pm_people_df_1, pm_people_df_2, pm_people_df_3, pm_people_df_4, pm_people_df_5,
#   pm_people_df_6, pm_people_df_7, pm_people_df_8, pm_people_df_9, pm_people_df_10,
#   pm_people_df_11, pm_people_df_12, pm_people_df_13, pm_people_df_14, pm_people_df_15,
#   pm_people_df_16, pm_people_df_17, pm_people_df_18, pm_people_df_19, pm_people_df_20,
#   pm_people_df_21, pm_people_df_22, pm_people_df_list, pm_a)
```

#pm_patients_df
rm unuseful col
```{r}
# pm_patients_df <- pm_patients_df[, -1]
# str(pm_patients_df)
```

change colnames
```{r}
# colnames(pm_patients_df) <- c("year", "month", "county", "district", "gender", "nation", "age", "number")
```

change the "age" between 0 and 4 into "00-04"
change the "age" of "5-9" into "05-09"
```{r}
# for(i in 1:nrow(pm_patients_df)){
#   if(any(pm_patients_df[i, 7] == 0:4)){
#     pm_patients_df[i, 7] <- "00-04"
#   }
#   if(pm_patients_df[i, 7] == "5-9"){
#     pm_patients_df[i, 7] <- "05-09"
#   }
# }
```

at column "nation", change chinese words to T and F
if "本國籍", then T
```{r}
# pm_patients_df[, 6] <- pm_patients_df[, 6] == "本國籍"
```

#response_death_list
year 106 to 101
```{r}
# for(i in response_death_list){
#  print(all(is.na(i[, 5])))
#  response_vec <- 0
#  print(1:ncol(i))
#  for(j in 1:ncol(i)){
#    print(response_vec)
#    if(all(is.na(i[, j]))){
#      print(response_vec)
#      vec[j] <- -1
#    }else{
#      print(response_vec)
#      vec[j] <- 1
#    }
#    print(response_vec)
#    print(i[, vec])
#  }
# }
# 
# 
# pm_list_106to101 <- list(pm_death_106, pm_death_105, pm_death_104, pm_death_103, pm_death_102, pm_death_101)
for(i in 1:6){
  pm_death_list[[i]] <- pm_death_list[[i]][c(-1:-5, -29), ]
  colnames(pm_death_list[[i]]) <- c("county", "deaths", "death rate", "standardized mortality ratio", 
                                    "M_deaths", "M_death rate", "M_standardized mortality ratio", 
                                    "F_deaths", "F_death rate", "F_standardized mortality ratio")
#  print(pm_death_list[[i]])
}

pm_death_106 <- pm_death_list[[1]]
pm_death_105 <- pm_death_list[[2]]
pm_death_104 <- pm_death_list[[3]]
pm_death_103 <- pm_death_list[[4]]
pm_death_102 <- pm_death_list[[5]]
pm_death_101 <- pm_death_list[[6]]

pm_death_106 <- cbind(pm_death_106, year = 2017)
pm_death_105 <- cbind(pm_death_105, year = 2016)
pm_death_104 <- cbind(pm_death_104, year = 2015)
pm_death_103 <- cbind(pm_death_103, year = 2014)
pm_death_102 <- cbind(pm_death_102, year = 2013)
pm_death_101 <- cbind(pm_death_101, year = 2012)

pm_death_total <- rbind(pm_death_101, pm_death_102, pm_death_103, pm_death_104, pm_death_105, pm_death_106)

# response_death_106 <- response_death_106[c(-1:-5, -29), ]
# 
# colnames(response_death_106) <- c("county", "deaths", "death rate", "standardized mortality ratio", "M_deaths", "M_death rate", "M_standardized mortality ratio", "F_deaths", "F_death rate", "F_standardized mortality ratio")
```

#response_death_list2
year 106 to 
```{r}

for(i in 1:6){
  pm_death_list2[[i]] <- pm_death_list2[[i]][c(-1:-3, -27), ]
  colnames(pm_death_list2[[i]]) <- c("county", "deaths", "death rate", "standardized mortality ratio", 
                                     "M_deaths", "M_death rate", "M_standardized mortality ratio", 
                                     "F_deaths", "F_death rate", "F_standardized mortality ratio")
}

pm_death2_106 <- pm_death_list2[[1]]
pm_death2_105 <- pm_death_list2[[2]]
pm_death2_104 <- pm_death_list2[[3]]
pm_death2_103 <- pm_death_list2[[4]]
pm_death2_102 <- pm_death_list2[[5]]
pm_death2_101 <- pm_death_list2[[6]]

pm_death2_106[8, 1] <- "桃園市"
pm_death2_105[8, 1] <- "桃園市"
pm_death2_104[8, 1] <- "桃園市"
pm_death2_103[8, 1] <- "桃園市"
pm_death2_102[8, 1] <- "桃園市"
pm_death2_101[8, 1] <- "桃園市"

pm_death2_106 <- cbind(pm_death2_106, year = 2017)
pm_death2_105 <- cbind(pm_death2_105, year = 2016)
pm_death2_104 <- cbind(pm_death2_104, year = 2015)
pm_death2_103 <- cbind(pm_death2_103, year = 2014)
pm_death2_102 <- cbind(pm_death2_102, year = 2013)
pm_death2_101 <- cbind(pm_death2_101, year = 2012)

pm_death2_total <- rbind(pm_death2_101, pm_death2_102, pm_death2_103, 
                         pm_death2_104, pm_death2_105, pm_death2_106)

# for(i in 7:15){
#  for(j in 1:nrow(pm_death_list[[i]])){
#    pm_vec <- 0
#    if(all(is.na(pm_death_list[[i]][j, ]))){
#      pm_vec[j] <- 0
#    }else{
#      pm_vec[j] <- 1
#    }
# 
#    pm_death_list[[i]] <- pm_death_list[[i]][pm_vec, ]
#  }
# 
#  for(j in 1:ncol(pm_death_list[[i]])){
#    pm_vec <- 0
#    if(all(is.na(pm_death_list[[i]][, j]))){
#      pm_vec[j] <- 0
#    }else{
#      pm_vec[j] <- 1
#    }
# 
#     pm_death_list[[i]] <- pm_death_list[[i]][, pm_vec]
#   }
# }
```

view
```{r}

```












