---
title: "SA_analysis"
author: "Pan"
date: "2019/6/7"
output: html_document
---
```{r,include = FALSE}
require(ggplot2)
library(readr)
library(tidyverse)
library(tidyr)
library(readxl)
library(xlsx)
library(ggplot2)
```

```{r eval=FALSE, warning=FALSE, include=FALSE}
distinct_electric_year <- read_excel("C:/Users/user/Documents/GitHub/1072Rproject/clear_data/distinct_electric_year.xlsx", 
    col_types = c("text", "text", "numeric", 
        "numeric", "text", "text"))%>%
  mutate(year=year+1911)
```




```{r}
#analysis CE year
distinct_electric_year
#五都 
six_city <-c("1","31","32","17","21","2")



#六都近年用電

distinct_electric_year%>%
  group_by(county_code,county,year)%>%
  summarize(kWh=sum(kWh))%>%
  filter(county_code %in% six_city)%>%
  ggplot(aes(x=year,y=kWh,
                color=county)) +
  geom_line()+
  geom_point()+
  ggtitle('六都近年用電量趨勢')+
  theme_bw()


```




```{r eval=FALSE, warning=FALSE, include=FALSE}
#跑很久
#import data 

distinct_electric_month <-
  read_excel("C:/Users/user/Documents/GitHub/1072Rproject/clear_data/distinct_electric_month.xlsx",
             col_types = c("text", "text", "skip", 
        "numeric", "text", "text", "numeric", 
        "numeric"))
```




#分析CE month
```{r}

#line 跑步出來

summary(distinct_electric_month)

distinct_electric_month%>%
  mutate(month=as.factor(month))%>%
  group_by(county_code,county,year,month)%>%
  summarize(kWh=sum(value))%>%
  ungroup()%>%
  group_by(county_code,county,month)%>%
  summarise(kWh=mean(kWh))%>%
  filter(county_code %in% six_city)%>%
  ggplot(aes(x=month,y=(kWh),
                color=county,group = county)) +
  geom_line()+
  geom_point()+
  ggtitle('六都2015-2019各月份用電量趨勢')+
  theme_bw()
```


#整理PM_CE各年資料
```{r eval=FALSE, warning=FALSE, include=FALSE}
pm_withcodes <- read_excel("C:/Users/user/Documents/GitHub/1072Rproject/pm_withcodes.xlsx", 
     col_types = c("skip", "skip", "text", 
         "text", "text", "numeric", "numeric", 
         "numeric", "numeric", "text", "text", 
         "text", "text"),
     col_names=c("site","year","month","PM2.5day","PM10day",
     "PM2.5","PM10","county","distinct","distinct_code",'county_code'),
     skip=1)
pm_withcodes

distinct_electric_year
#先整理出各縣市各區PM年平均,總PMday
pm_year<-pm_withcodes%>%
  mutate(year=as.numeric(year))%>%
  group_by(site,year,county_code,distinct_code)%>%
  summarize(PM2.5day=mean(PM2.5day),
            PM10day=mean(PM10day),
            PM2.5=mean(PM2.5,na.rm=T),
            PM10=mean(PM10,na.rm=T))%>%
  arrange(county_code)
pm_year
distinct_electric_year


pm_ce_year<-pm_year%>%
  inner_join(distinct_electric_year,
             by=c("year",'distinct_code',"county_code"))%>%
  arrange(distinct_code)


 # write.xlsx(as.data.frame(pm_ce_year), "epa_electric_yearly.xlsx",sheetName = "yearly",col.names = T, row.names = F, append = F)

#合併PM_CE各區資料(變成各縣市)
pm_ce_year_county<-pm_ce_year%>%
  group_by(year,county,county_code)%>%
  summarize(PM2.5day=mean(PM2.5day),
            PM10day=mean(PM10day),
            PM2.5=mean(PM2.5,na.rm=T),
            PM10=mean(PM10,na.rm=T),
            kWh=mean(kWh))%>%
  arrange(county_code)
pm_ce_year_county

#write.xlsx(as.data.frame(pm_ce_year_county), "epa_electric_yearly_county.xlsx",sheetName = "yearly",col.names = T, row.names = F, append = F)

```
#整理PM_CE各月資料

```{r}
pm_ce_month<-pm_withcodes%>%
  mutate(year=as.numeric(year),
         month=as.numeric(month))%>%
  inner_join(distinct_electric_month,
             by=c("year","month",'distinct_code',"county_code"))%>%
  select(-county.y,-distinct.y)%>%
  rename(distinct=distinct.x,county=county.x,kWh=value)%>%
  arrange(distinct_code,year,month)


distinct_electric_month
pm_ce_month

#  write.xlsx(as.data.frame(pm_ce_month), "epa_electric_monthly.xlsx",sheetName = "monthly",col.names = T, row.names = F, append = F)

#合併PM_CE各區資料(變成各縣市)
pm_ce_month_county<-pm_ce_month%>%
  group_by(year,month,county,county_code)%>%
  summarize(PM2.5day=mean(PM2.5day),
            PM10day=mean(PM10day),
            PM2.5=mean(PM2.5,na.rm=T),
            PM10=mean(PM10,na.rm=T),
            kWh=mean(kWh))%>%arrange(county_code)

pm_ce_month_county

#  write.xlsx(as.data.frame(pm_ce_month_county), "epa_electric_monthly_county.xlsx",sheetName = "monthly",col.names = T, row.names = F, append = F)
```


#PM VS CE year
LEVEL:整年
group:縣市平均

```{r}

pm_ce_year_county%>%
  ggplot() +
  geom_point(aes(x=log(kWh),
           y=PM2.5,
           color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=PM2.5),method = "lm") +
  theme_bw()+
  ggtitle('各縣市年均用電量與測站PM2.5濃度關係')
  


pm_ce_year_county%>%
filter(county_code %in% six_city)%>%
  ggplot() +
  geom_point(aes(x=log(kWh),
           y=PM2.5,
           color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=PM2.5),method = "lm") +
  theme_bw()+
  ggtitle('六都年均用電量與測站PM2.5濃度關係')

#summary(lm(formula = log(kWh) ~ PM2.5,data=pm_ce_year))
```



```{r}
#合併PM CE 月份 資料 



pm_ce_month%>%
  ggplot() +
  geom_point(aes(x=log(kWh),
           y=PM2.5,color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=PM2.5),method = "lm") +
  theme_bw()+
  ggtitle('各區月均用電量與測站PM2.5濃度關係')

pm_ce_month_county%>%
  ggplot() +
  geom_point(aes(x=log(kWh),
           y=PM2.5,color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=PM2.5),method = "lm") +
  theme_bw()+
  ggtitle('各縣市月均用電量與測站PM2.5濃度關係')



#    reg<-lm(formula = log(kWh) ~ PM2.5,data=pm_ce_month)
# summary(reg)

```


#看是否跟月份有關
```{r}
pm_ce_month%>%
  mutate(month=as.factor(month))%>%
  group_by(year,month,county_code,county)%>%
  summarize(PM2.5day=mean(PM2.5day),
            PM10day=mean(PM10day),
            PM2.5=mean(PM2.5,na.rm=T),
            PM10=mean(PM10,na.rm=T),
            kWh=mean(value))%>%
  arrange(county_code)%>%
  ggplot() +
  geom_point(aes(x=log(kWh),
           y=PM2.5,color=month)) +
  geom_smooth(aes(x=log(kWh),           
                   y=PM2.5),method = "lm") +
  theme_bw()

#似乎有 看看月分布
pm_ce_month%>%
  mutate(month=as.factor(month))%>%
  group_by(year,month,county_code,county)%>%
  summarize(PM2.5day=mean(PM2.5day),
            PM10day=mean(PM10day),
            PM2.5=mean(PM2.5,na.rm=T),
            PM10=mean(PM10,na.rm=T),
            kWh=mean(value))%>%
  arrange(county_code)%>%
  filter(county_code%in%five_city)%>%
  ggplot() +
  geom_point(aes(x=log(kWh),
           y=PM2.5,color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=PM2.5),method = "lm") +
  facet_wrap(~month)+
  theme_bw()



```


排放量清冊 
```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
#clean TEDS
#有point,line,plane
TEDS_point <- read_excel("C:/Users/user/Documents/GitHub/1072Rproject/TEDS9.0.xlsx",
                         sheet='point',
                         col_types = c("text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric")) 

EDS_p_clear<-TEDS_point%>%
  gather(year,result,-type,-county,-county_code)%>%
  spread(key =  type, value =  result)%>%
  mutate(year=as.numeric(year)+1911)%>%
  mutate(year=as.factor(year))%>%
  arrange(county_code,year)
TEDS_p_clear

TEDS_plane <- read_excel("C:/Users/user/Documents/GitHub/1072Rproject/TEDS9.0.xlsx",
                         sheet='plane',
                         col_types = c("text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric", "numeric", "numeric",
        "numeric")) 
TEDS_plane_clear<-TEDS_plane%>%
  gather(year,result,-type,-county,-county_code)%>%
  spread(key =  type, value =  result)%>%
  mutate(year=as.numeric(year)+1911)%>%
  mutate(year=as.factor(year))%>%
  arrange(county_code,year)
TEDS_plane_clear

```

```{r}

#作圖 玩TED point
TEDS_p_clear%>%
  na.omit%>%
  ggplot()+
  geom_line(aes(x=year,           
                   y=PM2.5,group=county,
                   color=county))+
    theme_bw()

TEDS_p_clear%>%
  filter(county_code %in% five_city)%>%
  ggplot()+
  geom_line(aes(x=year,           
                   y=PM2.5,group=county,
                   color=county))+
    theme_bw()


#不知為何無摺線
TEDS_plane_clear%>%
  filter(county_code %in% five_city)%>%
  ggplot()+
  geom_point(aes(x=year,           
                   y=PM2.5,
                   color=county))+
    theme_bw()

```




```{r}
#TEDS point source VS CE
TED_p_ce<-distinct_electric_year%>%
  mutate(year=as.factor(year))%>%
  group_by(year,county_code,county)%>%
  summarise(kWh=sum(kWh))%>%
  inner_join(TEDS_p_clear,by=c('year',"county_code"))%>%
  select(-county.y)%>%
  rename(county=county.x)

TED_p_ce
TED_p_ce%>%
  ggplot() +                        
    geom_point(aes(x=log(kWh),           
                   y=log(PM2.5),
                   color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=log(PM2.5)),method = "lm")+
    theme_bw()

 #檢查R squared
summary(lm(formula = log(kWh) ~ log(PM2.5),data=TED_p_ce
  ))


```



```{r}
#TEDS plane source VS CE
#點源
TEDplane_ce<-distinct_electric_year%>%
  mutate(year=as.factor(year))%>%
  group_by(year,county_code,county)%>%
  summarise(kWh=sum(kWh))%>%
  inner_join(TEDS_plane_clear,by=c('year',"county_code"))%>%
  select(-county.y)%>%
  rename(county=county.x)


TEDplane_ce%>%
  filter(county_code %in% five_city)%>%
  ggplot() +                        
    geom_point(aes(x=log(kWh),           
                   y=(PM2.5),
                   color=county)) +
  geom_smooth(aes(x=log(kWh),           
                   y=(PM2.5)),method = "lm")+
    theme_bw()

 #檢查R squared
summary(lm(formula = log(kWh) ~ PM2.5,data=TEDplane_ce%>%
  filter(county_code %in% five_city)))


#面源

```

#TEDS點源與PM關係

```{r}
#把PM資料整理成各縣市LEVEL

TED_PM<-pm_year%>%
  group_by(county_code,year)%>%
  summarize(epaPM2.5day=mean(PM2.5day),
            epaPM10day=mean(PM10day),
            epaPM2.5=mean(PM2.5),
            epaPM10=mean(PM10))%>%
  mutate(year=as.factor(year))%>%
  inner_join(TEDS_p_clear,by=c('year',"county_code"))
    


TED_PM%>%
  filter(county_code %in% five_city)%>%
  ggplot() +                        
    geom_point(aes(x=PM2.5,           
                   y=epaPM2.5,
                   color=county)) +
  geom_smooth(aes(x=PM2.5,           
                   y=epaPM2.5),method = "lm")+
  facet_wrap(~county)
    theme_bw()

 #檢查R squared
summary(lm(formula = PM2.5 ~ epaPM2.5,data=TED_PM%>%
  filter(county_code %in% five_city)))

```
#TEDS面源與PM關係
```{r}
#把PM資料整理成各縣市LEVEL

TED_PM_plane<-pm_year%>%
  group_by(county_code,year)%>%
  summarize(epaPM2.5day=mean(PM2.5day),
            epaPM10day=mean(PM10day),
            epaPM2.5=mean(PM2.5),
            epaPM10=mean(PM10))%>%
  mutate(year=as.factor(year))%>%
  inner_join(TEDS_plane_clear,by=c('year',"county_code"))

TED_PM_plane%>%
  filter(county_code %in% five_city)%>%
  ggplot() +                        
    geom_point(aes(x=PM2.5,           
                   y=epaPM2.5,
                   color=county)) +
  geom_smooth(aes(x=PM2.5,           
                   y=epaPM2.5),method = "lm")+theme_bw()

 #檢查R squared
summary(lm(formula = PM2.5 ~ epaPM2.5,data=TED_PM%>%
  filter(county_code %in% five_city)))

```