---
title: "pm2.5"
author: "leon_x123"
date: "23 May 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## fix languege
```{r}
Sys.setlocale("LC_CTYPE", locale="Chinese")
```

function: read multi worksheet from xlsx
```{r}
library(XLConnect)

pm_importWorksheets <- function(filename) {
    workbook <- loadWorkbook(filename)
    sheet_names <- getSheets(workbook)
    names(sheet_names) <- sheet_names
    sheet_list <- lapply(sheet_names, function(.sheet){
        readWorksheet(object=workbook, .sheet)})
}
```

reading multi worksheet from xlsx
```{r}
pm_death_list <- 
  pm_importWorksheets(filename = "C:/Users/ASUS/Downloads/1.2-24各縣市肺炎死亡概況.xls")

pm_death2_list <- 
  pm_importWorksheets(filename = "C:/Users/ASUS/Downloads/1.2-25各縣市慢性下呼吸道疾病死亡概況.xls")

pm_regionCode_list <- 
  pm_importWorksheets(filename = "C:/Users/ASUS/Desktop/workPlace/Taiwan_code.xlsx")
pm_regionCode_county_df <- pm_regionCode_list[[2]]

pm_population <- 
  pm_importWorksheets(filename = "C:/Users/ASUS/Desktop/workPlace/y0s1-00000.xls")

```

## tidy data
#pm_death_list
year 106 to 101
```{r}
for(i in 1:6){
  pm_death_list[[i]] <- pm_death_list[[i]][c(-1:-6, -29), c(-3, -4, -6, -7, -9, -10)]
  colnames(pm_death_list[[i]]) <- c("county", "deaths", "M_deaths", "F_deaths")
}

pm_death_106 <- pm_death_list[[1]]
pm_death_105 <- pm_death_list[[2]]
pm_death_104 <- pm_death_list[[3]]
pm_death_103 <- pm_death_list[[4]]
pm_death_102 <- pm_death_list[[5]]
pm_death_101 <- pm_death_list[[6]]

pm_death_102[7, 1] <- 
  pm_death_101[7, 1] <- "桃園市"

pm_death_106 <- cbind(pm_death_106, year = 2017)
pm_death_105 <- cbind(pm_death_105, year = 2016)
pm_death_104 <- cbind(pm_death_104, year = 2015)
pm_death_103 <- cbind(pm_death_103, year = 2014)
pm_death_102 <- cbind(pm_death_102, year = 2013)
pm_death_101 <- cbind(pm_death_101, year = 2012)

pm_death_total <- rbind(pm_death_101, pm_death_102, pm_death_103, pm_death_104, pm_death_105, pm_death_106)
```

#response_death2_list
year 106 to 101
```{r}
for(i in 1:6){
  pm_death2_list[[i]] <- pm_death2_list[[i]][c(-1:-4, -27), c(-3, -4, -6, -7, -9, -10)]
  colnames(pm_death2_list[[i]]) <- c("county", "deaths", "M_deaths", "F_deaths")
}

pm_death2_106 <- pm_death2_list[[1]]
pm_death2_105 <- pm_death2_list[[2]]
pm_death2_104 <- pm_death2_list[[3]]
pm_death2_103 <- pm_death2_list[[4]]
pm_death2_102 <- pm_death2_list[[5]]
pm_death2_101 <- pm_death2_list[[6]]

pm_death2_106[7, 1] <- 
  pm_death2_105[7, 1] <- 
  pm_death2_104[7, 1] <- 
  pm_death2_103[7, 1] <- 
  pm_death2_102[7, 1] <- 
  pm_death2_101[7, 1] <- "桃園市"

pm_death2_106 <- cbind(pm_death2_106, year = 2017)
pm_death2_105 <- cbind(pm_death2_105, year = 2016)
pm_death2_104 <- cbind(pm_death2_104, year = 2015)
pm_death2_103 <- cbind(pm_death2_103, year = 2014)
pm_death2_102 <- cbind(pm_death2_102, year = 2013)
pm_death2_101 <- cbind(pm_death2_101, year = 2012)

pm_death2_total <- rbind(pm_death2_101, pm_death2_102, pm_death2_103, 
                         pm_death2_104, pm_death2_105, pm_death2_106)
```

add county code
```{r}
pm_death_total <- cbind(pm_death_total, county_code = NA)
pm_death2_total <- cbind(pm_death2_total, county_code = NA)

for(i in 1:nrow(pm_death_total)){
  for(j in 1:nrow(pm_regionCode_county_df)){
    if(pm_death_total[i, 1] == pm_regionCode_county_df[j, 1]){
      pm_death_total[i, ncol(pm_death_total)] <- pm_regionCode_county_df[j, 2]
    }
  }
}

for(i in 1:nrow(pm_death2_total)){
  for(j in 1:nrow(pm_regionCode_county_df)){
    if(pm_death2_total[i, 1] == pm_regionCode_county_df[j, 1]){
      pm_death2_total[i, ncol(pm_death2_total)] <- pm_regionCode_county_df[j, 2]
    }
  }
}
```

add col: population
```{r}
pm_death_total <- cbind(pm_death_total, population = NA, M_population = NA, F_population = NA)
pm_death2_total <- cbind(pm_death2_total, population = NA, M_population = NA, F_population = NA)

pm_population[[6]][29, 1] <- 
  pm_population[[7]][29, 1] <- "桃園市"

for(i in 1:6){
  for(j in 1:22){
    for(k in 1:nrow(pm_population[[8-i]])){
      if(is.na(pm_population[[8-i]][k, 1])){
      }else if((pm_death_total[i*22+j-22, 1]) == gsub(" ", "", pm_population[[8-i]][k, 1])){
        pm_death_total[i*22+j-22, 7] <- pm_population[[8-i]][k-1, 3]
        pm_death_total[i*22+j-22, 8] <- pm_population[[8-i]][k, 3]
        pm_death_total[i*22+j-22, 9] <- pm_population[[8-i]][k+1, 3]
      }
    }
  }
}

for(i in 1:6){
  for(j in 1:22){
    for(k in 1:nrow(pm_population[[8-i]])){
      if(is.na(pm_population[[8-i]][k, 1])){
      }else if((pm_death2_total[i*22+j-22, 1]) == gsub(" ", "", pm_population[[8-i]][k, 1])){
        pm_death2_total[i*22+j-22, 7] <- pm_population[[8-i]][k-1, 3]
        pm_death2_total[i*22+j-22, 8] <- pm_population[[8-i]][k, 3]
        pm_death2_total[i*22+j-22, 9] <- pm_population[[8-i]][k+1, 3]
      }
    }
  }
}
```

turn character into numeric
```{r}
for(i in 1:8){
  for(j in 1:nrow(pm_death_total)){
    if(pm_death_total[j, i+1] == "-"){
      pm_death_total[j, i+1] <- 0
    }
  }
  
  pm_death_total[, i+1] <- as.numeric(gsub(",", "", pm_death_total[, i+1]))
}

for(i in 1:8){
  for(j in 1:nrow(pm_death2_total)){
    if(pm_death2_total[j, i+1] == "-"){
      pm_death2_total[j, i+1] <- 0
    }
  }
  
  pm_death2_total[, i+1] <- as.numeric(gsub(",", "", pm_death2_total[, i+1]))
}
```

add col: ratio
```{r}
library(magrittr)
library(dplyr)

pm_death_total <- pm_death_total %>% 
  mutate(ratio = deaths / population, M_ratio = M_deaths / M_population, F_ratio = F_deaths / F_population)

pm_death2_total <- pm_death2_total %>% 
  mutate(ratio = deaths / population, M_ratio = M_deaths / M_population, F_ratio = F_deaths / F_population)
```

write xlsx
warning: library xlsx is conflict with library XLConnect
```{r}
# library("xlsx")
# 
# write.xlsx(pm_death_total, "pneumonia.xlsx", sheetName = "deaths QwQ",
#            col.names = T, row.names = F, append = F)
# 
# write.xlsx(pm_death2_total, "chronic_lower_respiratory_diseases.xlsx", sheetName = "deaths QwQ",
#            col.names = T, row.names = F, append = F)
```

view
```{r}

```

rm
```{r}
rm(pm_death_list, pm_death2_list, pm_death_101, pm_death_102, pm_death_103, pm_death_104, pm_death_105, pm_death_106, pm_death2_101, pm_death2_102, pm_death2_103, pm_death2_104, pm_death2_105, pm_death2_106, pm_regionCode_list, pm_regionCode_county_df, pm_population)
```



